server:
  port: 9999

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
      enabled: false

backbase:
  api:
    override-5xx-error-messages: false
  security:
    public:
      paths: /**

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  sleuth:
    sampler:
      probability: 0.5
  liquibase:
    enabled: false #change this to true to create DB schema on server start
    change-log: classpath:/database/changelog-master.xml
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=dis_otp
    username: sa
    password: Myp@aaw0rd #Set/Use your local mssql password.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mssql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

logging:
  level:
    com.kib.bb: DEBUG
    org.springframework: INFO
    com.backbase: DEBUG
