server:
  port: 0

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
      enabled: false

backbase:
  api:
    override-5xx-error-messages: false
  security:
    public:
      paths: /service-api/v1/resend/bind

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  sleuth:
    sampler:
      probability: 0.5
  liquibase:
    enabled: false #change this to true to create DB schema on server start
    change-log: classpath:/database/changelog-master.xml
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=dis_otp
    username: sa
    password: Myp@aaw0rd #Set/Use your local mssql password.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mssql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

logging:
  level:
    com.kib.bb: DEBUG
    org.springframework: INFO
    com.backbase: DEBUG

kib:
  future:
    timeout:
      millisecond: 500 # 0.5 second
  otp:
    cooldown:
      seconds: 15
    max:
      initiations:
        amount: 15
        span: 600
      attempts: 3
      resends: 3
    size:
      default: 6
    expiry:
      # 5 minutes
      seconds: 300
    template:
      default: "Your OTP is {otp}"  #NK-5020
  thread-pool:
    core-pool:
      size: 5
    max-pool:
      size: 10
  communication:
    serviceId:
      notifications: "dis-notifications-service"
      data: "dis-data-service"
      user-manager: "user-manager"